AllCops:
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20
Metrics/AbcSize:
  Include: ["app/controllers/*"]
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

<<<<<<< HEAD
Layout/HashAlignment:
=======
Layout/AlignHash:
>>>>>>> 112907a... ADD RUBOCOP, EDIT README
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
<<<<<<< HEAD
  EnforcedStyle: indented
=======
  EnforcedStyle: indented
>>>>>>> 112907a... ADD RUBOCOP, EDIT README
